/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ball.gltf 
Author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/placid-iridescence-use-j-k-keys-cd6ac4264b6241fc834fc97bd7244541
Title: Placid Iridescence (Use J + K Keys)
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations, OrbitControls } from "@react-three/drei";

export function Ball(props) {
  const group = useRef();
  //https://sketchfab.com/3d-models/placid-iridescence-use-j-k-keys-cd6ac4264b6241fc834fc97bd7244541
  const { nodes, materials, animations } = useGLTF("/ball/ball.gltf");
  console.log("🚀 ~ Ball ~ nodes:", nodes);
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <OrbitControls />
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Sphere_0">
                <mesh
                  name="Object_4"
                  geometry={nodes.Object_4.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Sphere001_1" scale={0.897}>
                <mesh
                  name="Object_6"
                  geometry={nodes.Object_6.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Sphere002_2" scale={0.797}>
                <mesh
                  name="Object_8"
                  geometry={nodes.Object_8.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Sphere003_3" scale={0.696}>
                <mesh
                  name="Object_10"
                  geometry={nodes.Object_10.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Sphere004_4" scale={0.603}>
                <mesh
                  name="Object_12"
                  geometry={nodes.Object_12.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Sphere005_5" scale={0.5}>
                <mesh
                  name="Object_14"
                  geometry={nodes.Object_14.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Circle_7"
                rotation={[0.615, -Math.PI / 6, -0.615]}
                scale={1.941}
              >
                <group name="Sphere006_6" scale={0.528}>
                  <mesh
                    name="Object_17"
                    geometry={nodes.Object_17.geometry}
                    material={materials["Material.002"]}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/ball/ball.gltf");
